### ISSUE TITLE
GNOME Shell theme doesn't do RGB subpixel antialiasing

### ISSUE THREAD

**Issue by Eneen** [adapta-project/adapta-gtk-theme#510] opened 2017-09-18 19:34 UTC
Please take a look @ screenshot. There is RGB subpixel antialiasing on GTK theme but it doesn't work on shell theme. It's been fixed on on System76 pop theme (based on adapta as I think).
![adapta_subpixel_smoothing_bug](https://user-images.githubusercontent.com/25537418/30560768-319ac4da-9cb9-11e7-9149-7ba3d79f33c6.png)

**Comment by tista500** [comment] 2017-09-20 14:19
We can not find any issues with your blurred image.

**Comment by tista500** [comment] 2017-09-20 14:20
Lack of font infomations and issue_templete.

**Comment by Eneen** [comment] 2017-09-20 14:47
![adapta_subpixel_smoothing_bug_enl](https://user-images.githubusercontent.com/25537418/30650462-3a2dbeca-9e23-11e7-8a35-d60727757ed0.png)
It should be visible now.
There is no RGB subsampling on shell theme. I've set Rotobo 10 as GTK+ font to compare.

**Comment by Eneen** [comment] 2017-09-20 15:01
**Reporter info**

 ```
 * Distribution - Ubuntu 17.10 Artful Ardvark
 * Gtk+ 3.0 version - 3.22.21
 * Desktop environment - GNOME Shell
 * Display server protocol - X11
 ```

**Adapta version (if you knew)**
Current screenshot from Adapta 3.91.2.168


**Related Application and/or Shell theming (or name of widget)**
Same Adapta


**Actual issue**
No RGB Font subsampling on GNOME Shell theme, greyscale subsampling only.


**Steps to reproduce (if you knew)**
Just right-click on any app title-bar to see


**Expected behaviour**
There should be RGB subsampling


**Other Note (feature-request, question, etc...)**
System76 Pop theme based on Adapta has correct subsampling.

**Comment by tista500** [comment] 2017-09-20 16:04
o_O?

Let me see the output of this: `xrandr --verbose | grep Subpixel`

**Comment by Eneen** [comment] 2017-09-20 17:55
> olo@olo-VirtualBox:~$ xrandr --verbose |grep Subpixel
> 	Subpixel:   unknown
> 	Subpixel:   unknown
> 	Subpixel:   unknown
> 	Subpixel:   unknown

**Comment by tista500** [comment] 2017-09-20 18:33
How could we do subpixel smoothing without RGB order info? I'm really afraid that you're explaining about cogl Wayland mode... X11 has already workaround for such 'unknown' orders, cogl with Xorg automatically fallbacks to Horizontal RGB order if xrandr could not determine the proper RGB orders from graphics environments, but cogl Wayland mode can't. I don't have any ideas why this issue was related to user-themes...

**Comment by Eneen** [comment] 2017-09-20 18:39
I'm sure using Xorg (Nvidia drivers).
Take a look @ Adwaita shell theme:
![adwaita_shell_theme_rgb](https://user-images.githubusercontent.com/25537418/30661303-d82835ea-9e43-11e7-93f3-fd69baf78bc1.png)

**Comment by tista500** [comment] 2017-10-02 08:33
I can't reproduce this at least in en_US.UTF-8 anyhow, so I close this time.

**Closed by tista500** 2017-10-02 08:33 UTC
Labels: unable to reproduce
