### ISSUE TITLE
Barely readable labels in some GTK3 apps

### ISSUE THREAD

**Issue by PeterFeicht** [adapta-project/adapta-gtk-theme#372] opened 2017-03-14 11:36 UTC
**Reporter info**

 ```
 * Distribution - Arch
 * Gtk+ 3.0 version - 3.22.10
 * Desktop environment - Xfce 4.12
 ```

**Adapta version**

3.89.4.148

**Related Application and/or Shell theming (or name of widget)**

Gnome Builder in particular, but also Evince

**Actual issue**

There are some labels in the "title bars" of these apps which are very dark on black background, making them barely readable.

A partial screenshot of Builder and Evince should be here:
![builder](https://cloud.githubusercontent.com/assets/7085977/23898725/6d37027e-08b2-11e7-8b8d-f033b050ad61.png)
![evince](https://cloud.githubusercontent.com/assets/7085977/23898732/72045824-08b2-11e7-8668-b49934b8a63e.png)

**Comment by tista500** [comment] 2017-03-14 11:43
> Gnome Builder in particular,

The duplicate of #371.

> but also Evince

That label should be under `:disabled` pseudo-class, unclickable, so This works as I expected.

Won't fix, closed.

**Closed by tista500** 2017-03-14 11:43 UTC

**Comment by PeterFeicht** [comment] 2017-03-14 13:19
That's some timing, I forget to search for an existing bug one time and someone reports it an hour earlier. Sorry for the noise :-)

**Comment by tista500** [comment] 2017-03-14 13:22
No problem. ;)
