### ISSUE TITLE
Wrong rendering of current position element (audacious, smplayer).

### ISSUE THREAD

**Issue by viewizard** [adapta-project/adapta-gtk-theme#392] opened 2017-04-17 13:45 UTC
**Reporter info**

 ```
 * Distribution - Gentoo
 * Gtk+ 3.0 version - 3.22.11
 * Desktop environment - XFCE4
 ```

**Adapta version (if you knew)**
3.90.0.65

**Related Application and/or Shell theming (or name of widget)**
audacious 3.7.1 (gtk+ v2 or gtk+ v3 gui - same issue on both)
smplayer 16.1.0 (qt4 with gtk+ style)

**Actual issue**
Wrong rendering of current position element:

audacious
![audacious](https://cloud.githubusercontent.com/assets/15098562/25090173/6b5765dc-238a-11e7-9461-cb8f887b868d.png)

smplayer
![smplayer](https://cloud.githubusercontent.com/assets/15098562/25090174/6b71e0a6-238a-11e7-8b71-13c27224b5ef.png)

**Comment by tista500** [comment] 2017-04-17 14:08
o_O??

Here's my Audacius 3.7.2 with Gtk+ 2 interface:
![screenshot from 2017-04-17 22-56-53](https://cloud.githubusercontent.com/assets/6073622/25091136/74938eea-23c2-11e7-80c8-b7108071aa5b.png)

I don't know that app has Gtk+ 3.x interface, but at least I could not reproduce. I need to check the older release of Ubuntu as well...

Regards.

**Comment by tista500** [comment] 2017-04-17 14:43
I still could not reproduce by using Audacious 3.6.2 on my Ubuntu 16.04. And I'm not an user of SMPlayer, so haven't any clue what happened their Qt-Gtk backend.

**Comment by viewizard** [comment] 2017-04-17 15:17
In the same time don't have any issues with pulse audio control:
![pulse](https://cloud.githubusercontent.com/assets/15098562/25092359/fd5b3d72-2395-11e7-90e1-fa75dca6c09d.png)

Could this be connected to custom color usage? I have inkscape v0.91 installed and use custom color configuration:
--with-selection_color=#00BCD4
--with-second_selection_color=#4DD0E1
--with-accent_color=#4DB6AC
--with-suggestion_color=#009688
--with-destruction-color=#FF5252

tista500, could you please look at your QT Configuration Tool?
![qt2](https://cloud.githubusercontent.com/assets/15098562/25092798/e9ede116-2397-11e7-9b6c-528d05f9cea5.png)
I also noticed, that Qt-Gtk backend does not render a line for me:
![smplayer](https://cloud.githubusercontent.com/assets/15098562/25092875/4d4b5568-2398-11e7-9aaf-cc7153bc3f9e.png)
Do you have it in your QT Configuration Tool?

I am just worry, why I have this issue with Adapta, but Arc theme work just fine. :-(

**Comment by tista500** [comment] 2017-04-17 15:58
> I am just worry, why I have this issue with Adapta, but Arc theme work just fine. :-(

Please go back to Arc. I'm really tired with that crazy backend, so I need much more time to track down.

**Comment by viewizard** [comment] 2017-04-17 16:37
But... I just updated from Adapta v3.89.2.53 to Adapta v3.90.0.65 and faced with this issue in audacious, was never used Arc...

**Comment by tista500** [comment] 2017-04-17 19:23
Committed: https://github.com/adapta-project/adapta-gtk-theme/commit/92adcd730b1051aecd6a74404cf511d5afccfc4f

Personally I really dislike to run Qt apps inside the GNOME environments, so I'm not testing enough though, but that commit would improve a bit better than before.

Regards.

**Closed by tista500** 2017-04-17 19:23 UTC
Labels: unable to reproduce

**Comment by tista500** [comment] 2017-04-19 14:34
Rev.81 Release: https://github.com/adapta-project/adapta-gtk-theme/releases/tag/3.90.0.81

If your generated pixmaps had incorrect image-sizes, please check this rev.81 release. I've changed rendering scripts to get more precise version number from Inkscape.

Regards.
