### ISSUE TITLE
[Feature Request] Tweak GNOME Weather Today / Tomorrow switcher

### ISSUE THREAD

**Issue by JoshStrobl** [adapta-project/adapta-gtk-theme#443] opened 2017-06-27 21:31 UTC
**Reporter info**

 ```
 * Distribution - Solus
 * Gtk+ 3.0 version - 3.22.16
 * Desktop environment - GNOME
 ```

**Adapta version (if you knew)**

3.91.0.126

**Related Application and/or Shell theming (or name of widget)**

Application question is GNOME Weather, Shell theme is Adapta.

**Actual issue**

Not an "issue" per-say, just that I think the Today / Tomorrow switcher in GNOME Weather looks odd against an image and then mostly transparent elements. Gives the feeling that it's just floating there with no real relation to elements around it.

Screenshot below

![gnome-weather-adapta](https://user-images.githubusercontent.com/156574/27610838-9f41b690-5b98-11e7-8e6b-744a6ff4c3b0.png)

**Steps to reproduce (if you knew)**

- Be sensible, use Adapta.
- Install and open up GNOME Weather

**Expected behaviour**

The switcher feels more tied to the weather list below it. Whether it's transparent to match the background, or the weather list is opaque.

**Other Note (feature-request, question, etc...)**

No idea what, if anything, you can do about this. GTK theming isn't really my forte.

**Comment by tista500** [comment] 2017-06-27 22:01
You mean we should add more responsive design for that stack-siwtcher like this?: https://git.gnome.org/browse/gnome-weather/tree/data/application.css#n14

**Comment by JoshStrobl** [comment] 2017-06-27 22:03
Yea that'd be fantastic.

**Comment by ikeydoherty** [comment] 2017-06-27 22:22
@tista500 random observation, and you probably don't get told this nearly enough, but you're awesome, dude. Seriously.

As an aside, apologies for the work I'm causing you with the upstream Budgie changes every other minute >_>

**Comment by tista500** [comment] 2017-06-28 00:06
@JoshStrobl,

Please give me a bit more time to make theming up... This change will become huge code insertions, if I could read Gnome-Weather's codes correctly.

@ikeydoherty,

The recent changes on my Adapta are caused by my 'hidden' code problems (trust me, that's true). So you don't have to be sorry about it.  ;-)

**Comment by JoshStrobl** [comment] 2017-06-28 00:11
> Please give me a bit more time to make theming up...

Oh trust me, I'm not here to rush you. The fact it's gonna happen at some point is good enough to me :+1: Lemme know if / where I can pitch in monetarily and I will.

**Comment by tista500** [comment] 2017-06-28 08:20
@JoshStrobl,

3 commits have landed...
Although some pieces of colour balance and brightness distributions might not be perfect, I roughly styled responsive colour definitions.

But remember that there's 'un-changeable' things  related to upstream's stylesheet...

Regards.

**Closed by tista500** 2017-06-28 08:20 UTC
Labels: enhancement

**Comment by JoshStrobl** [comment] 2017-06-28 21:42
Confirmed, looks fantastic. Thanks again :heart:

![screenshot from 2017-06-29 00-41-16](https://user-images.githubusercontent.com/156574/27661646-c1e23ea6-5c63-11e7-8a6b-83ff326db18f.png)
