### ISSUE TITLE
[Question] Why use "global dark theme"?

### ISSUE THREAD

**Issue by DarthWound** [adapta-project/adapta-gtk-theme#411] opened 2017-05-07 10:49 UTC
Hello there, thank you for this great theme!

However I wonder why we have to enable "global dark theme" while using Nokto variant to truly have a dark theme. I mean, for Adwaita or Flat-Plat or Arc or almost anything else, all we have to do is select the dark variant in theme selection, and that's all, and it never brings any issue.

It's much simpler for scripting too (I use a script to switch between day and night using gsettings).

It's a true question and not a rant, as I would like to know if it would be possible to modify this behaviour sooner or later or if this is technically impossible due to this theme "architecture".

**Comment by tista500** [comment] 2017-05-07 14:50
> almost anything else

Is that correct?
If I remembered well, "Adwaita-Dark" was unveiled in 3.22 release cycle. Flat-Plat released such separated dark variants in Mar. So I don't have any ideas why you said those have had such separated dark variants from the start... Arc might have them from the start though.

> it never brings any issue.

Never!?
Once light/dark variants are completely separated, we no longer mix the variants anymore. For example, Graphics designers usually works with dark-variant raster/vector graphics applications like PhotoShop, Inkscape, Gimp, Blender and more. So I created dark variant for Gtk+ 2.x. On the other hand, most of Web contents still depend on light variant, and famous Web browsers too. It means dark variant browsers brought ton of issues to us in past...

Nokto is for the dark Gtk+ 2.x theming from the start, not for Gtk+ 3.x. In Gtk+ 3.x applications, our default colour variant is light now and then. If most of web contents can have dark variant widget design as default, we may switch to dark variant as default. 
 
Adapta provides the possibility that we can mix the 2 x 2 variants, like light-firefox/chrome, dark-gimp, dark-totem, dark-inkscape, light-corebird ...etc. This is for adaptive design because there's no guildelines we should have exactly same UI colours in all of applications and graphical shells.

In Android, the only one thing that employs dark variant as default is "Android Wear 2.0". Although "Night Mode" was unveiled in M release cycle, but still light variant is the default, maybe O, too. 

> if it would be possible to modify this behaviour sooner or later or if this is technically impossible due to this theme "architecture".

In technically, we can mimic the behaviour of Arc and Flat-Plat. But I won't. Feel free to move to other themes which you don't have to tweak the "global dark" option, I promise I never force you to use Adapta. Arc and Flat-Plat is great than mine.

Regards.

**Comment by luisfpg** [comment] 2017-05-07 16:41
Yes, this was strange for me as well, because, well, Nokto is supposed to be dark :).
Anyhow, even selecting Adapta Nokto with global dark theme enabled, Eclipse (Neon - 4.6.3) was still picking the light variant (for some widgets only!!!).
The fix for me was to (as root) copy gtk-dark.css over gtk.css in /usr/share/themes/Adapta-Nokto/gtk-3.22. I did the same for Adapta-Nokto-Eta.
Doing so will not require the "use global dark theme" tweak. Also, as Adapta-Nokto just links to Adapta, it will also make Adapta use a dark theme, but in my case, I always use dark themes anyhow (better for the eyes, you know :-) ).
I suppose any new updates in the theme will require one to do this trick again.
BTW, as I understood this is like this by design. But, please, consider linking the gtk.css to gtk-dark.css in Nokto variants. It would make Adapta more standard. I understand the default is light in most systems, but this is what Nokto is for, right?

**Comment by tista500** [comment] 2017-05-07 16:53
@luisfpg,

If you felt strange, no need to use Adaita, right? ;)

**Comment by tista500** [comment] 2017-05-07 16:59
Committed: https://github.com/adapta-project/adapta-gtk-theme/commit/3414e4f35a233fa3ef52857e6fe0aaac859a4cf4

**Comment by luisfpg** [comment] 2017-05-07 17:09
@tista500 Wrong.
C'mon, Adapta is a very nice theme. Please, be as nice to your users.
You could just say this is the desired behavior and marking the thing as 'Won't fix' instead of just telling us to not use your theme.
BTW, Adapta does have a global dark variant for GTK 2. The amount of work to do a global dark variant is just a link (and maybe a new name).
But ok, this is my last post on the subject. It is a pity that suggestions for actually improving the theme were  responded in such a silly and rude way.

**Comment by tista500** [comment] 2017-05-07 17:13
> You could just say this is the desired behavior and marking the thing as 'Won't fix' instead of just telling us to not use your theme.

I've already said: 
> In technically, we can mimic the behaviour of Arc and Flat-Plat. But I won't.

**Comment by tista500** [comment] 2017-05-07 17:22
I will keep the current styling until:

* Upstream dropped `gtk-application-prefer-dark-theme` key.
* Android next release had dark variant as default.

Closed.

**Closed by tista500** 2017-05-07 17:22 UTC
Labels: question
