### ISSUE TITLE
Nemo-Sidebar unreadable

### ISSUE THREAD

**Issue by w4grfw** [adapta-project/adapta-gtk-theme#646] opened 2018-02-24 10:37 UTC
The bookmarks in the sidebar are not readable
![nemo](https://user-images.githubusercontent.com/13349836/36629488-8c8ebf8a-1956-11e8-9a84-98b0206a6790.png)

 ```
 * Distribution - Xubuntu 17.10
 * Gtk+ 3.0 version - 3.22.24-0ubuntu
 * Desktop environment - Xfce
 * Display server protocol - X11
 ```

Adapta version: 3.93.0.143-0ubuntu1~artful1

**Comment by tista500** [comment] 2018-02-24 10:55
o_O?

Could not reproduce with Nemo 3.4.5 and 3.6.5 either.

**Comment by w4grfw** [comment] 2018-02-24 11:02
I’m using nemo_3.6.5-1~webupd8~artful01_amd64.deb (https://launchpad.net/~webupd8team/+archive/ubuntu/nemo3)

**Comment by tista500** [comment] 2018-02-28 11:45
Ah, that PPA has ton of downstream patches for Nemo. and `fix-sidebar-style-with-gtk320.patch` causes this issue.

So I won't fix for that downstream patch which was neither contained in the stock package of main repository nor https://launchpad.net/~gwendal-lebihan-dev/+archive/ubuntu/cinnamon-nightly PPA.

That's quite unofficial PPA specific thing. Won't fix, sorry.

**Closed by tista500** 2018-02-28 11:45 UTC
Labels: unable to reproduce
