### ISSUE TITLE
Close button look weird on firefox 58.0.1 (64-bit) on latest adapta build

### ISSUE THREAD

**Issue by ahloiscreamo** [adapta-project/adapta-gtk-theme#634] opened 2018-02-09 08:55 UTC
The previous version of adapta have none of this issues 
reference- 
![screenshot from 2018-02-09 16-54-10](https://user-images.githubusercontent.com/9318372/36019330-e2b29dda-0db9-11e8-9c98-992754e9b83b.png)

 ```
 * Distribution -fedora 27
 * Gtk+ 3.0 version -3.22.26
 * Desktop environment -gnome
 * Display server protocol - Wayland
 ```

**Comment by tista500** [comment] 2018-02-09 10:36
Why don't you guys read our release comments? : https://github.com/adapta-project/adapta-gtk-theme/releases/tag/3.93.0.106

That's not our issue but fxxkin' upstream issue in 58 and 59.

**Comment by tista500** [comment] 2018-02-09 10:39
The duplicate of this: #584

**Closed by tista500** 2018-02-09 10:39 UTC
Labels: duplicate
