### ISSUE TITLE
[Firefox] unable to see which url-bar item is hovered

### ISSUE THREAD

**Issue by HeikoAdams** [adapta-project/adapta-gtk-theme#357] opened 2017-02-21 18:35 UTC
**Reporter info**

 ```
 * Distribution - Fedora 25
 * Gtk+ 3.0 version - GKT 3.22
 * Desktop environment - Gnome 3.22
 ```

**Adapta version (if you knew)**
latest git master

**Related Application and/or Shell theming (or name of widget)**
Firefox

**Actual issue**
It is currently immpossible to see which url-bar item is hovered because it seems the hovering-color is transparent

![bildschirmfoto vom 2017-02-21 19-35-16](https://cloud.githubusercontent.com/assets/1418818/23179058/e90972a2-f86c-11e6-8e97-1897d976b394.png)

**Comment by prefiks** [comment] 2017-02-21 20:09
I am seeing this too, looks like firefox is using color/background from textview view:selected, textview view:selected:focus to get colors for it

**Comment by tista500** [comment] 2017-02-21 20:11
The duplicate of #347.

**Comment by tista500** [comment] 2017-02-21 20:28
@prefiks,

Could you verify that ugly firefox patch was really using `textview view` node instead of `textview .view`? Because there's no Gtk+ 3.x widgets named `view` node in the world as far as I know. GtkView should be defined by `.view` style-class... :(

Regards.

**Comment by tista500** [comment] 2017-02-21 20:40
A workaround was committed: https://github.com/adapta-project/adapta-gtk-theme/commit/bd8c6fa99e1c13fbd9b0b734a40a20324c107d73

Regards.

**Closed by tista500** 2017-02-21 20:40 UTC
Labels: duplicate

**Comment by prefiks** [comment] 2017-02-21 20:45
Ah, sorry it should be textview text (i should copy/paste that from my css tweak instead writing this from head)

**Comment by tista500** [comment] 2017-02-21 20:54
Who accepted that patch!?
`textview text` should only have `selection` node instead of any `:selected` style-classes...:/
Completely upstream issue (patch issue).

**Comment by tista500** [comment] 2017-02-21 21:00
The 2nd shot was committed: https://github.com/adapta-project/adapta-gtk-theme/commit/bfb251664067f4f604365b182ccdb2c91e9900a5

Closed.

**Comment by prefiks** [comment] 2017-02-21 21:02
This is not fedora specific i am seeing this in original mozilla's firefox

**Comment by tista500** [comment] 2017-02-21 22:06
Ah, OK.
Anyway thanks for your tracking this issue down.
