### ISSUE TITLE
atom text editor menu bar highlight issue

### ISSUE THREAD

**Issue by gusdemayo** [adapta-project/adapta-gtk-theme#323] opened 2017-01-06 14:40 UTC
**Reporter info**

 ```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - 3.22.6-1
 * Desktop environment - GNOME 3.22
 ```

**Adapta version (if you knew)**
3.89.2.53-1

**Related Application and/or Shell theming (or name of widget)**
Atom Text Editor

**Actual issue**
In the atom text editor the menu bar selected options are highlighted
without the text color changing, so the options are covered up when selected
![screenshot from 2017-01-06 08-39-56](https://cloud.githubusercontent.com/assets/22549145/21721005/c5418508-d3eb-11e6-85ca-f0e5ec6974d6.png)

**Comment by tista500** [comment] 2017-01-06 21:09
This is the duplicate of this issue: #216.
We can not handle those context menus properly rendered by Electron with Gtk+ 3.x backend.

And GtkMenuBar, GtkMenuItem and most of things have incorrect theming...

Regards.

**Comment by tista500** [comment] 2017-01-07 09:03
Check if this commit https://github.com/adapta-project/adapta-gtk-theme/commit/94eb85a96dfc47c159e7c3af65a85c5acd18b157 could solve this issue...

**Comment by magiruuvelvet** [comment] 2017-01-07 09:22
This one seems to fix the menu bar at least. Items still have the same issue.
![screenshot_20170107_101727](https://cloud.githubusercontent.com/assets/13280758/21740741/dc556c14-d4c2-11e6-8472-5e6f82d0d5d4.png)

**Comment by tista500** [comment] 2017-01-08 03:16
Please check the 2nd-shot: https://github.com/adapta-project/adapta-gtk-theme/commit/87fc030b1c28e4effdd2f9e8a7f19cef93504a68

Regards.

**Comment by magiruuvelvet** [comment] 2017-01-08 17:22
Looks good now :)

![screenshot_20170108_181716](https://cloud.githubusercontent.com/assets/13280758/21751890/0fb37abc-d5cf-11e6-95cc-c13e18b2e952.png)

**Closed** 2017-01-08 23:43 UTC
Labels: duplicate, wontfix
