### ISSUE TITLE
Gnome-shell Activities overview - WindowCaption not centered in Wayland

### ISSUE THREAD

**Issue by pmargeti34** [adapta-project/adapta-gtk-theme#521] opened 2017-09-28 14:40 UTC
```
 * Distribution - Arch Linux
 * Gtk+ 3.0 version - 3.22.21+37+ga57630b30c-1
 * Desktop environment - Gnome
 * Display server protocol - X11 or Wayland? Wayland
 ```

**Adapta version (if you knew)**
https://github.com/adapta-project/adapta-gtk-theme/commit/e33c6d292f35d84f81aa56884fe80eeeee2d5b96

**Related Application and/or Shell theming (or name of widget)**
Gnome-shell Activities overview

**Actual issue**
Text that appears at the bottom of the window when you mouse over it is not centered in gnome-shell overview

**Steps to reproduce (if you knew)**
Open Activities menu, mouse over a running program
![screenshot from 2017-09-28 16-38-38](https://user-images.githubusercontent.com/13254332/30972677-8a493828-a46b-11e7-9ece-b460778c6b45.png)

**Expected behaviour**
Application name is either centered or doesn't have padding added to the right.

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment] 2017-09-28 15:02
We do not support Cantarell fonts. And I could not reproduce...

**Comment by pmargeti34** [comment] 2017-09-28 15:07
Those are Noto Sans, or at least should be...
![screenshot from 2017-09-28 17-06-29](https://user-images.githubusercontent.com/13254332/30974236-7a49374e-a46f-11e7-840b-10616628bcd4.png)

**Comment by tista500** [comment] 2017-09-28 15:23
https://github.com/adapta-project/adapta-gtk-theme#typography

> In Gnome-Shell 3.26 theming, we've switched to Roboto already.

And as your 1st attached shot shown, take a look at the term "Nightly" (especially the letter "l"), then I don't think Noto/Roboto was used.

**Comment by tista500** [comment] 2017-09-28 15:47
Upper: Roboto Regular 9.75pt
Lower: Cantarell Regular 9.75pt
![roboto_vs_cantarell](https://user-images.githubusercontent.com/6073622/30976283-62944482-a4af-11e7-9170-4f53050e8970.png)

Sample application: Chromium  63.0.3213.3 max'd on Yoga 260 B125HAN02.2 1920x1080 IPS screen

**Comment by pmargeti34** [comment] 2017-09-28 16:55
Well spotted about wrong font being used, but I'm not entirely sure how that's possible. Cantarell isn't set, the PKGBUILD doesn't seem to specify anything either. I'm completely confused as to why it's not using Noto Sans.

Also, if it matters, my display resolution is 2560x1080.

**Comment by tista500** [comment] 2017-09-28 17:10
https://github.com/adapta-project/adapta-gtk-theme/blob/master/shell/sass/gnome-shell/3.26/_common.scss#L21

As I said, we've switched to Roboto completely, then Noto-Sans is not used anymore in Gnome-Shell-3.26 theming.

**Comment by tista500** [comment] 2017-09-28 17:23
I now can reproduce. Indeed, Wayland specific. And it seems to happen on all user-themes and built-in Adwaita as well. So it might be the upstream issue in cogl-pango and/or gnome-shell itself...

**Comment by tista500** [comment] 2017-09-28 17:35
Upstream report: https://bugzilla.gnome.org/show_bug.cgi?id=787260

**Comment by tista500** [comment] 2017-09-28 17:55
Unfortunately there's few things to do with this issue from theme-side, so I set this "Won't fix", sorry.

**Closed by tista500** 2017-09-28 17:55 UTC
Labels: upstream issue
