### ISSUE TITLE
Cut off Dialog in all GTK3 applications

### ISSUE THREAD

**Issue by JoshStrobl** [adapta-project/adapta-gtk-theme#530] opened 2017-10-09 16:23 UTC
**Reporter info**

 ```
 * Distribution - Solus
 * Gtk+ 3.0 version - 3.22.24
 * Desktop environment - GNOME Shell
 * Display server protocol - X11 or Wayland? X11
 ```

**Adapta version (if you knew)**

3.91.2.228

**Related Application and/or Shell theming (or name of widget)**

GTK3 applications such as Gedit, Nautilus and GNOME MPV

**Actual issue**

Bottom border of dialogs in GTK3 applications are getting cut off.

**Steps to reproduce (if you knew)**

Open up a GTK3 application such as Nautilus, right click on a folder and get its properties.

![screenshot from 2017-10-09 19-19-38](https://user-images.githubusercontent.com/156574/31348084-23e0e760-ad27-11e7-9c3e-bc551c3d8eec.png)

![screenshot from 2017-10-09 19-22-42](https://user-images.githubusercontent.com/156574/31348121-3c6859bc-ad27-11e7-9083-1a60a2dbb4a3.png)

**Expected behaviour**

Dialogs not get cut off :smile:

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment] 2017-10-09 16:54
o_O?

I could not reproduce at least on my proposed-Artful, Gnome-Shell/Mutter 3.26.1 X11 session...

![screenshot from 2017-10-10 01-51-27](https://user-images.githubusercontent.com/6073622/31349333-c63aeae8-ad5d-11e7-8284-9cbbb0d9a225.png)

**Comment by tista500** [comment] 2017-10-09 17:16
And Nautilus 3.26.0 "Preferences" GtkDialog with 'modal' mode on Wayland session:
![screenshot from 2017-10-10 02-14-40](https://user-images.githubusercontent.com/6073622/31350122-f1c39dec-ad60-11e7-8b28-0c8f741f353f.png)

I could not see any issues about the truncation of drop-shadows anyhow... :(

**Comment by JoshStrobl** [comment] 2017-10-09 17:17
Okay so sounds like something is on drugs here, I'll continue poking around :+1:

**Comment by ikeydoherty** [comment] 2017-10-09 17:17
Note we're only using X11 on Solus currently - and windows don't become truncated under Wayland

**Comment by tista500** [comment] 2017-10-09 19:22
Trial commit: https://github.com/adapta-project/adapta-gtk-theme/commit/243d2e366e8fc11719f9b5283a0a68f39a992c65

That commit makes no sense for me at all, but it may or may not affect the drop-shadow property of GtkDialog's `dialog` node... ;(

**Comment by ikeydoherty** [comment] 2017-10-09 19:53
Attempting local build

**Comment by ikeydoherty** [comment] 2017-10-09 20:03
In Solus now: https://dev.solus-project.com/R338:f46b61c867b6d302fada1ae4908329f4d54cd407

Genuinely does fix it for me :rofl: - I'll get @JoshStrobl to test it once it lands in the binary repo

Awesome work as always @tista500 - thanks! (And sorry for having the *weirdest* issues all the time!)

**Comment by JoshStrobl** [comment] 2017-10-09 20:18
Can confirm that it resolved the issue. Seriously good work @tista500, can't thank you enough. I shall give you the luxury of marking this resolved :)

**Comment by tista500** [comment] 2017-10-09 20:42
OK, my blind shot seemed to work properly as I expected, so let's close this...

Regards.

**Closed by tista500** 2017-10-09 20:42 UTC
Labels: unable to reproduce
