### ISSUE TITLE
[Feature Request] Adapta-icon-theme

### ISSUE THREAD

**Issue by ceyhunnabiyev** [adapta-project/adapta-gtk-theme#451] opened 2017-07-12 18:22 UTC

**Comment by bil-elmoussaoui** [comment] 2017-07-12 18:37
Duplicate of https://github.com/adapta-project/adapta-gtk-theme/issues/12
An icon theme is a too much effort. I think supporting Paper icon theme which is a great GTK icon theme which follows some of the Material design guidelines instead of reinventing the wheel.

**Closed** 2017-07-12 19:17 UTC
Labels: duplicate
