### ISSUE TITLE
right click menu black

### ISSUE THREAD

**Issue by kaladin87** [adapta-project/adapta-gtk-theme#531] opened 2017-10-10 09:50 UTC
**Reporter info**

 ```
 * Distribution - Ubuntu 17.04
 * Gtk+ 3.0 version - 3.22.11 i think
 * Desktop environment - XFCE
 * Display server protocol - X11 
 ```

**Adapta version (if you knew)**

**Related Application and/or Shell theming (or name of widget)**

Thunar / Desktop, not in chromium/Firefox tho

**Actual issue**
right click menus are dark/black

**Steps to reproduce (if you knew)**

right click somewhere

**Expected behaviour**
context menu that pops up is dark

**Other Note (feature-request, question, etc...)**
love the theme ! :+1:  would be great if this would be fixed

**Comment by tista500** [comment] 2017-10-10 16:25
I could not reproduce on my locally installed proposed-Artful/ Xfce4 4.12.1 & Thunar 1.6.12.

**Comment by jazz7787** [comment] 2017-10-11 16:58
![87e1e170-1152-419d-9a26-9ade0b42e7bc](https://user-images.githubusercontent.com/775128/31454560-19edee02-aeb6-11e7-939a-0909ee3e9dd6.jpeg)
 This is how it looks like.

**Comment by tista500** [comment] 2017-10-11 17:19
o_O?

![screenshot from 2017-10-12 02-16-54](https://user-images.githubusercontent.com/6073622/31455769-9bbb9172-aef3-11e7-990f-8181ea4bf780.png)

**Comment by jazz7787** [comment] 2017-10-11 17:22
Well this is definitely wierd :)

2017-10-11 19:19 GMT+02:00 Tista <notifications@github.com>:

**Comment by tista500** [comment] 2017-10-11 17:30
Have you already tried logout & re-login? Thunar is one of the co-process of xfce-session to handle the desktop contents.

**Comment by tista500** [comment] 2017-10-15 22:49
I couldn't reproduce this yet even on Zesty, so close this time. I may or may not re-open this when I could reproduce and track down...

**Closed by tista500** 2017-10-15 22:49 UTC
Labels: unable to reproduce
