### ISSUE TITLE
Can't see text buttons.

### ISSUE THREAD

**Issue by josehfurtado** [adapta-project/adapta-gtk-theme#645] opened 2018-02-18 19:50 UTC
**Reporter info**

 ```
 * Distribution - Ubuntu Xenial
 * Gtk+ 3.0 version - 3.18.9
 * Desktop environment - XFCE
 * Display server protocol - X11
 ```

**Adapta version (if you knew)**
PPA updated

**Related Application and/or Shell theming (or name of widget)**
Adapta Nokto/ Playonlinux.

**Actual issue**
I can't see what butons does in Playonlinux. Most of applications looks nice.

**Steps to reproduce (if you knew)**
When select a aplication in main window can see something is wrong but config panel is a real problem. Buttons like "add" and "remove" virtual machine cannot be identified. "Install" button is cut.
![captura de tela_2018-02-18_16-00-45](https://user-images.githubusercontent.com/30763086/36356101-a35ae610-14cb-11e8-879d-9c6f02d6cf20.png)

**Expected behaviour**
Maybe less edge and little bigger buttons.

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment] 2018-02-19 08:56
https://github.com/PlayOnLinux/POL-POM-4/blob/master/python/configure.py#L334

We don't support such apps overrides Gtk+ 2's element height/width with non-sense fixed (maximum) height/width. Those approaches are damned problematic especially when we're scaling font-scaling-factor > 1. So the truncation would potentially happen in all Gtk+ 2 themes. It means that app completely ignores Gtk+ 2 theme's `xthickness`, `ythickness` and `inner-border` properties. The stem of the issue is in upstream.

Our `-eta` variants can reduce the internal spacing of those elements, but `-eta` variants do not  support Gtk+ 3.18.x distros (requires Gtk+ 3.20.x or higher).

So won't fix, sorry.

**Closed by tista500** 2018-02-19 08:56 UTC
