### ISSUE TITLE
Some captions with bold font, some with regular.

### ISSUE THREAD

**Issue by gandriyko** [adapta-project/adapta-gtk-theme#267] opened 2016-11-03 11:38 UTC
**Reporter info**

 ```
 * Distribution - Arch
 * Gtk+ 3.0 version - 3.22.2+
 * Desktop environment - Mate 1.16.0-1
 ```

**Adapta version (if you knew)**
adapta-gtk-theme-3.22.2.44
**Related Application and/or Shell theming (or name of widget)**
taskbar

**Actual issue**
Some captions with bold font, some with regular.
![screenshot at 2016-11-03 13-12-54](https://cloud.githubusercontent.com/assets/1176487/19964468/7a51c222-a1ca-11e6-8525-c744bb5bb6cd.png)

**Steps to reproduce (if you knew)**
Always

**Expected behaviour**
 Maybe all captions will display with regular font.

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment] 2016-11-03 12:03
MUST!?

**Comment by tista500** [comment] 2016-11-03 12:30
I'm really not sure but anyway I committed: https://github.com/adapta-project/adapta-gtk-theme/commit/ac2a656e76db7eed27171ab2df74d3bc9377e06b

I don't have any other solutions...

Regards.

**Comment by tista500** [comment] 2016-11-09 04:14
I can't reproduce this issue anyhow, so closed in this time.

Regards.

**Closed by tista500** 2016-11-09 04:14 UTC
