### ISSUE TITLE
Problems with Gimp Single Window

### ISSUE THREAD

**Issue by andreale141** [adapta-project/adapta-gtk-theme#490] opened 2017-08-23 19:49 UTC
**Reporter info** Problems with Gimp Single Window
Theme leaves useless single window mode in Gimp. Images open but get Gimp to minimized window and disappears window maximize button. It leaves him useless. Gimp can only function correctly with unlocked sidebars. I already did tests with other topics and Gimp works well. Thank you very much for taking care of me and congratulations to this great work.

 ```
 * Distribution - Linux Mint 18.2
 * Gtk+ 3.0 version - Cinnamon 3.4.6
 * Desktop environment - 
 * Display server protocol - X11 or Wayland?
 ```

**Adapta version (if you knew)** 3.91.2.57.0ubuntu1~xenial1

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**

**Steps to reproduce (if you knew)**

**Expected behaviour**

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment] 2017-08-28 14:50
Still I could not reproduce this, so currently close this, sorry. I will re-open this if it happened on my environments.

Closed.

**Closed by tista500** 2017-08-28 14:50 UTC
Labels: unable to reproduce
