### ISSUE TITLE
Launcher and menu bar problem

### ISSUE THREAD

**Issue by victorabr** [adapta-project/adapta-gtk-theme#307] opened 2016-12-12 17:37 UTC
```
 * Distribution - Ubuntu 16.10
 * Gtk+ 3.0 version - 3.20.9-1ubuntu2
 * Desktop environment - Unity
 ```

**Adapta version (if you knew)**
3.89.1.113-0ubuntu1~yakkety1

**Related Application and/or Shell theming (or name of widget)**
Launcher and menu bar.

**Actual issue**
Since the last updates (maybe 8/12) launcher icons are weird (with a colored background when openened) and a white line can be seen at the top of the desktop bar. (See: https://postimg.org/image/f80f6twnn/)

Installed a fresh ubuntu 16.10 on a VM and then directly installed the updates and adapta and this problem appeared too.
**Steps to reproduce (if you knew)**
Updating

//Adapta installed with PPA

**Comment by tista500** [comment] 2016-12-12 17:44
The duplicate of this report: #300. Please search the issues before posting.

**Comment by tista500** [comment] 2016-12-12 17:45
> a white line can be seen at the top of the desktop bar. (See:

What is the "desktop bar"?

**Comment by victorabr** [comment] 2016-12-12 18:08
Oh sorry it's the first time I use github.
the "desktop bar" is the bar on the top of the screen (you can see it in the screenshot) where you can check the time etc.As english is not my native language, I don't really know how to call it.
Normaly, this bar is flat but since the problem appeared, you can see a white reflect on it. (It's difficult to see this in the screenshot).
I've defined a semi transparent background with compiz, when using the solid bg I don't have this problem. (I don't know if this canbe considered as an Adapta bug)

**Comment by victorabr** [comment] 2016-12-12 18:16
And after following what you said on the previous bug report, icons are now fine but not the "search on your computer" one (the top first). It's still black

**Comment by tista500** [comment] 2016-12-13 00:39
> I don't really know how to call it.

We call it "Unity-panel".

> I've defined a semi transparent background with compiz,

I don't think this issue happened with the configurations via unity-tweak-tool. So I could not reproduce.

> I don't know if this canbe considered as an Adapta bug

Adapta does not support user-side tweaking of opacity/transparency.

> icons are now fine but not the "search on your computer" one (the top first). It's still black

I suspect this may be the issue of compositor you run. As I said above, I could not reproduce it via unity-tweak-tool. Check if this happened with Ambiance as well.

So I mark this issue "won't fix" as "unable to reproduce"

Regards.

**Closed** 2016-12-13 15:36 UTC
Labels: duplicate, wontfix

**Comment by tista500** [comment] 2017-01-09 05:12
> I've defined a semi transparent background with compiz, when using the solid bg I don't have this problem. (I don't know if this canbe considered as an Adapta bug)

See #325.
Unwanted vertically gradient (artifact) inside the unity-panel was fixed.
