### ISSUE TITLE
Failed to install in Archlinux 

### ISSUE THREAD

**Issue by bOlaE** [adapta-project/adapta-gtk-theme#363] opened 2017-03-06 06:56 UTC
**Reporter info**

 ```
 * Distribution - Archlinux
 * Gtk+ 3.0 version - 3.22.9
 * Desktop environment - XFCE
 ```

**Adapta version (if you knew)**

3.84.4.110

**Actual issue**

Making install in gtk
make[1] : on entre dans le répertoire « /tmp/yaourt-tmp-bola/aur-adapta-gtk-theme/src/adapta-gtk-theme-3.89.4.65/gtk »
make[2] : on entre dans le répertoire « /tmp/yaourt-tmp-bola/aur-adapta-gtk-theme/src/adapta-gtk-theme-3.89.4.65/gtk »
make[2]: rien à faire pour « install-exec-am ».
/usr/bin/mkdir -p /tmp/yaourt-tmp-bola/aur-adapta-gtk-theme/pkg/adapta-gtk-theme/usr/share/themes/Adapta
/usr/bin/mkdir -p /tmp/yaourt-tmp-bola/aur-adapta-gtk-theme/pkg/adapta-gtk-theme/usr/share/themes/Adapta-Nokto
/usr/bin/mkdir -p /tmp/yaourt-tmp-bola/aur-adapta-gtk-theme/pkg/adapta-gtk-theme/usr/share/themes/Adapta-Eta
/usr/bin/mkdir -p /tmp/yaourt-tmp-bola/aur-adapta-gtk-theme/pkg/adapta-gtk-theme/usr/share/themes/Adapta-Nokto-Eta
cp -Rv ./index.theme /tmp/yaourt-tmp-bola/aur-adapta-gtk-theme/pkg/adapta-gtk-theme/usr/share/themes/Adapta
'./index.theme' -> '/tmp/yaourt-tmp-bola/aur-adapta-gtk-theme/pkg/adapta-gtk-theme/usr/share/themes/Adapta/index.theme'
cp -Rv ./index.theme-nokto /tmp/yaourt-tmp-bola/aur-adapta-gtk-theme/pkg/adapta-gtk-theme/usr/share/themes/Adapta-Nokto/index.theme
'./index.theme-nokto' -> '/tmp/yaourt-tmp-bola/aur-adapta-gtk-theme/pkg/adapta-gtk-theme/usr/share/themes/Adapta-Nokto/index.theme'
cp -Rv ./index.theme-eta /tmp/yaourt-tmp-bola/aur-adapta-gtk-theme/pkg/adapta-gtk-theme/usr/share/themes/Adapta-Eta/index.theme
'./index.theme-eta' -> '/tmp/yaourt-tmp-bola/aur-adapta-gtk-theme/pkg/adapta-gtk-theme/usr/share/themes/Adapta-Eta/index.theme'
cp -Rv ./index.theme-nokto-eta /tmp/yaourt-tmp-bola/aur-adapta-gtk-theme/pkg/adapta-gtk-theme/usr/share/themes/Adapta-Nokto-Eta/index.theme
'./index.theme-nokto-eta' -> '/tmp/yaourt-tmp-bola/aur-adapta-gtk-theme/pkg/adapta-gtk-theme/usr/share/themes/Adapta-Nokto-Eta/index.theme'
/usr/bin/mkdir -p /tmp/yaourt-tmp-bola/aur-adapta-gtk-theme/pkg/adapta-gtk-theme/usr/share/themes/Adapta/gtk-3.0
cp -Rv ./gtk-3.18/gtk.css ./gtk-3.18/gtk-dark.css ./gtk-3.18/gtk.gresource ./asset/assets-gtk3/thumbnail@2.png ./asset/assets-gtk3/thumbnail.png /tmp/yaourt-tmp-bola/aur-adapta-gtk-theme/pkg/adapta-gtk-theme/usr/share/themes/Adapta/gtk-3.0
'./gtk-3.18/gtk.css' -> '/tmp/yaourt-tmp-bola/aur-adapta-gtk-theme/pkg/adapta-gtk-theme/usr/share/themes/Adapta/gtk-3.0/gtk.css'
'./gtk-3.18/gtk-dark.css' -> '/tmp/yaourt-tmp-bola/aur-adapta-gtk-theme/pkg/adapta-gtk-theme/usr/share/themes/Adapta/gtk-3.0/gtk-dark.css'
cp: impossible d'évaluer './gtk-3.18/gtk.gresource': Aucun fichier ou dossier de ce type
'./asset/assets-gtk3/thumbnail@2.png' -> '/tmp/yaourt-tmp-bola/aur-adapta-gtk-theme/pkg/adapta-gtk-theme/usr/share/themes/Adapta/gtk-3.0/thumbnail@2.png'
'./asset/assets-gtk3/thumbnail.png' -> '/tmp/yaourt-tmp-bola/aur-adapta-gtk-theme/pkg/adapta-gtk-theme/usr/share/themes/Adapta/gtk-3.0/thumbnail.png'
make[2]: *** [Makefile:998: install-data-local] Error 1
make[2] : on quitte le répertoire « /tmp/yaourt-tmp-bola/aur-adapta-gtk-theme/src/adapta-gtk-theme-3.89.4.65/gtk »
make[1]: *** [Makefile:789: install-am] Error 2
make[1] : on quitte le répertoire « /tmp/yaourt-tmp-bola/aur-adapta-gtk-theme/src/adapta-gtk-theme-3.89.4.65/gtk »
make: *** [Makefile:369: install-recursive] Error 1

**Steps to reproduce (if you knew)**

sudo make install

**Comment by tista500** [comment] 2017-03-06 08:25
I can't read localized log messages at all.
And the duplicate of #343?

> **Steps to reproduce (if you knew)**
> sudo make install

If you used package management system, please report precisely. what's the "yaourt"? :(

**Comment by bOlaE** [comment] 2017-03-06 09:45
Thanks for your answer,
I have installed it from the AUR with YAOURT and got this error. I have tried to install it from the source too and got the same error. I've already read #343 but the solution doesn't work for me.

./autogen.sh 
make
And I get this error we I execute the command "sudo make install" 

`Making install in gtk
make[1] : on entre dans le répertoire « /home/bola/Bureau/Adapta/gtk »
make[2] : on entre dans le répertoire « /home/bola/Bureau/Adapta/gtk »
make[2]: rien à faire pour « install-exec-am ».
/usr/bin/mkdir -p /usr/share/themes/Adapta
/usr/bin/mkdir -p /usr/share/themes/Adapta-Nokto
/usr/bin/mkdir -p /usr/share/themes/Adapta-Eta
/usr/bin/mkdir -p /usr/share/themes/Adapta-Nokto-Eta
cp -Rv ./index.theme /usr/share/themes/Adapta
'./index.theme' -> '/usr/share/themes/Adapta/index.theme'
cp -Rv ./index.theme-nokto /usr/share/themes/Adapta-Nokto/index.theme
'./index.theme-nokto' -> '/usr/share/themes/Adapta-Nokto/index.theme'
cp -Rv ./index.theme-eta /usr/share/themes/Adapta-Eta/index.theme
'./index.theme-eta' -> '/usr/share/themes/Adapta-Eta/index.theme'
cp -Rv ./index.theme-nokto-eta /usr/share/themes/Adapta-Nokto-Eta/index.theme
'./index.theme-nokto-eta' -> '/usr/share/themes/Adapta-Nokto-Eta/index.theme'
/usr/bin/mkdir -p /usr/share/themes/Adapta/gtk-3.0
cp -Rv ./gtk-3.18/gtk.css ./gtk-3.18/gtk-dark.css ./gtk-3.18/gtk.gresource ./asset/assets-gtk3/thumbnail@2.png ./asset/assets-gtk3/thumbnail.png /usr/share/themes/Adapta/gtk-3.0
'./gtk-3.18/gtk.css' -> '/usr/share/themes/Adapta/gtk-3.0/gtk.css'
'./gtk-3.18/gtk-dark.css' -> '/usr/share/themes/Adapta/gtk-3.0/gtk-dark.css'
cp: impossible d'évaluer './gtk-3.18/gtk.gresource': Aucun fichier ou dossier de ce type
'./asset/assets-gtk3/thumbnail@2.png' -> '/usr/share/themes/Adapta/gtk-3.0/thumbnail@2.png'
'./asset/assets-gtk3/thumbnail.png' -> '/usr/share/themes/Adapta/gtk-3.0/thumbnail.png'
make[2]: *** [Makefile:1010: install-data-local] Error 1
make[2] : on quitte le répertoire « /home/bola/Bureau/Adapta/gtk »
make[1]: *** [Makefile:801: install-am] Error 2
make[1] : on quitte le répertoire « /home/bola/Bureau/Adapta/gtk »
make: *** [Makefile:369: install-recursive] Error 1`

**Comment by tista500** [comment] 2017-03-10 09:06
Unfortunately I can't help this, sorry.

Closed.

**Closed by tista500** 2017-03-10 09:06 UTC
