### ISSUE TITLE
Gnome Shell crash and restart only once at startup

### ISSUE THREAD

**Issue by eypsum** [adapta-project/adapta-gtk-theme#205] opened 2016-08-26 00:50 UTC
**Reporter info**
H/W: Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
Distro: Ubuntu Gnome 16.04.1
Desktop: Gnome shell 3.18.5
Linux: 4.4.0-34

**Adapta version (if you knew)**
3.21.4+git20160824 or less

**Actual issue**
Gnome Shell crash and restart if with Adapta-Nokto gnome-shell theme(not gtk theme).
It no appears on the Adwaita gnome-shell theme (default shell theme).

**Steps to reproduce (if you knew)**
Step1. Loginned.
Step2. wait untill desktop appears.
Step3. take out short time on somthing or not.
Step4. Gnome Shell crash and restart with the new desktop.

**Expected behaviour**
Gnome Shell should not crash.

**Comment by tista500** [comment] 2016-08-26 15:55
I could not reproduce. :(
So what syslog said when re-starting Gnome-Shell?

Regards.

**Comment by eypsum** [comment] 2016-08-29 05:09
I attached the log file when gnom-shell crash on the Adapta-Nokto shell theme.
This issue seems to be related to the Unicode-based locale. 
Is the theme safe about the Locale based on Unicode ?
My desktop language is Korean.
so the desktop use the font called Nanum.

[01__usr_bin_gnome-shell.1000.crash.zip](https://github.com/tista500/Adapta/files/441679/01__usr_bin_gnome-shell.1000.crash.zip)

**Comment by tista500** [comment] 2016-08-29 07:40
o_O ?? gdb dump?
Hey hey, I said "what syslog said"?

> This issue seems to be related to the Unicode-based locale. 

So today most of locales use UTF-8... :(
And I could not reproduce on my en_US.UTF-8.

**Comment by tista500** [comment] 2016-08-29 07:43
You seems to have "Noto Sans CJK" as well, then your issue happened with Noto Sans, too?

**Comment by eypsum** [comment] 2016-08-29 10:23
Yes, I have Noto Sans CJK  font  like file attacted following.
![notosanscjk_font](https://cloud.githubusercontent.com/assets/20113770/18045829/d52be112-6e0f-11e6-82f8-2dc7e87dabf0.png)

I have never use Noto Sans.  
I still didn't try with it.

My font setting is about the default like following,
Window Title: Cantarell Bold. 11
Interface: Cantarell Regular 11
Document: Sans Regular 11
Fixed width: Ubuntu Monoe Regular 13, <-- this is only modified for me
and Nanum true type font is configured for Korean by FontConfig.

the syslog file you requested  is attached below
the file is part of whole. I culled out only parts related with 'Adapta' .
[syslog_with_Adapta.txt](https://github.com/tista500/Adapta/files/442188/syslog_with_Adapta.txt)

**Comment by tista500** [comment] 2016-08-29 11:21
```
Gtk-WARNING **: Error loading image 'file:///usr/share/themes/Adapta/gtk-3.0/assets/slider-horz-scale-has-marks-above-hover.png'
Gtk-WARNING **: Error loading image 'file:///usr/share/themes/Adapta/gtk-3.0/assets/slider-horz-scale-has-marks-above-hover@2.png'
Gtk-WARNING **: Error loading image 'file:///usr/share/themes/Adapta/gtk-3.0/assets/text-select-start-active.png'
```

o_O?
I don't know those PNG images, surely those were not included in current origin/master.

**Comment by tista500** [comment] 2016-09-04 18:07
No response, and I could not find the way to reproduce. Closed

**Comment by tista500** [comment] 2016-10-17 08:36
@eypsum,

So https://github.com/adapta-project/adapta-gtk-theme/issues/205#issuecomment-243097866 was fixed? Those should NOT happen with my package.

**Comment by eypsum** [comment] 2016-10-17 10:45
>> So #205 (comment) was fixed? Those should NOT happen with my package.
I am sorry I delayed response and my bad english.
Okay, those log appears no more. So I think that it has not a relation with a font or Unicode charset.
Since then, I have found  what Cogl error written in the syslog when Gnome shell crash, so it seems to be related with another thing.
I have written that something  to Ubuntu Gnome bug list.
Please see that from:  https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1619096
thanks.

**Comment by tista500** [comment] 2016-10-17 10:59
> I am sorry I delayed response and my bad english.

No need to be sorry because my english is bad as well. ;)

> I think that it has not a relation with a font or Unicode charset.

It's too early to decide theme-unrelated. Sometimes cogl may or may not crash with heavy-load on your GPUs. At least my Adapta is not the light-weight Gtk+/Gnome-Shell theme... So if devs/contributors answered your launchpad report and they might need some debugging with Adapta (theme-related), please let me know.

Anyway I'll keep this issue open.

Regards.

**Comment by eypsum** [comment] 2016-10-17 11:00
Today I tried to debug using Arc-Dark theme.
example, I replaced codes in  Arc-Dark's  gnome-shell.css with Adapta-Nokto's one.
Fortunatley Gnome not crashed on the modified Arc-Dark theme.

**Comment by eypsum** [comment] 2016-10-18 00:17
Okay I got it.

**Comment by esalgado** [comment] 2016-10-22 06:20
Hi! This also affects to me, every time I log in.

Thanks :)

**Comment by tista500** [comment] 2016-10-22 07:01
Greetings,

What your GPU is?
I have Intel and Radeon only, I'm not sure this related to GPU drivers though...

Regards.

**Comment by tista500** [comment] 2016-10-22 09:02
Spinner was rewritten: https://github.com/adapta-project/adapta-gtk-theme/commit/52c70a566e7271ea28c748f262249f7890e43c8e

**Comment by esalgado** [comment] 2016-10-22 09:20
Hi,

I have an integrated intel.
Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz

Thanks,

**Comment by eypsum** [comment] 2016-10-25 04:41
My PC's VGA card is  GeForce GT 610
lspci shows NVIDIA Corporation GF119 [GeForce GT 610] (rev a2)
and My desktop top(Ubuntu Gnome 16.04.1) is running on Nouveau.

**Comment by tista500** [comment] 2016-10-25 12:15
Fix missing noise-texture images: https://github.com/adapta-project/adapta-gtk-theme/commit/a68f43f6a351ff3c23a4ad41969b7df3f4e5dc36

**Comment by tista500** [comment] 2016-11-21 10:51
Fix incorrect image look-ups: https://github.com/adapta-project/adapta-gtk-theme/commit/cc683f4fa845627a95d81ff58912c41a57bd14e9

This might cause https://github.com/adapta-project/adapta-gtk-theme/issues/205#issuecomment-243097866...

**Comment by eypsum** [comment] 2016-11-21 23:46
I will hope to have new experience with this update.
Thanks a lot for your great job.

**Comment by esalgado** [comment] 2016-12-11 16:52
I'm sorry, I tried it again today and it keeps crashing :(

I attach a screenshot of the error ubuntu crash assistant gives me (I could not save it as txt sorry!)

Regards,

![captura de pantalla de 2016-12-11 17-51-06](https://cloud.githubusercontent.com/assets/977612/21081583/6d0a79b0-bfca-11e6-9aee-6410d55f86d7.png)

**Comment by tista500** [comment] 2016-12-13 14:28
Round the precision for font-size: https://github.com/adapta-project/adapta-gtk-theme/commit/624f65b8f1958088a1cfbd18551099d36f08da4d

This affects to the renderer of cogl-pango, it might be a bit more easier to compute the preferred_width/height...

Anyway I could not reproduce now and then.

**Comment by GXE3** [comment] 2017-02-03 23:43
I made a github account just to report that I found a fix for this issue on my computer. For me, it involved the "legacy-tray" class in the gnome-shell.css file.

To fix this, I opened gnome-shell.css (found in /Adapta/gnome-shell)and deleted all lines involving ".legacy-tray". After reloading the theme, gnome shell no longer crashed. This was the problematic code for me:

> .legacy-tray { padding: 0; border: 0 none transparent; background-color: #13191c; box-shadow: 0 0 transparent; }
> 
> .legacy-tray:ltr { border-radius: 0 2px 0 0; }
> 
> .legacy-tray:rtl { border-radius: 2px 0 0 0; }
> 
> .legacy-tray StButton { width: 24px; height: 24px; padding: 4px 4px 2px; border-radius: 2px; border: 2px solid #13191c; }
> 
> .legacy-tray StButton, .legacy-tray StButton * { color: rgba(236, 239, 241, 0.75); }
> 
> .legacy-tray StButton:hover, .legacy-tray StButton:focus { background-color: rgba(236, 239, 241, 0.12); }
> 
> .legacy-tray StButton:hover, .legacy-tray StButton:hover *, .legacy-tray StButton:focus, .legacy-tray StButton:focus * { color: #FFFFFF; }
> 
> .legacy-tray StButton:active { background-color: rgba(236, 239, 241, 0.2); }
> 
> .legacy-tray StButton:active, .legacy-tray StButton:active * { color: #FFFFFF; }
> 
> .legacy-tray StButton StIcon { icon-size: 24px; }
> 
> .legacy-tray-icon-box { spacing: 3px; }
> 
> .legacy-tray-icon-box:ltr { padding-left: 3px; }
> 
> .legacy-tray-icon-box:rtl { padding-right: 3px; }


Ubuntu Gnome 16.04
Gnome Shell 3.18
Nvidia GTX 960M
Intel® Core™ i7-6700HQ CPU @ 2.60GHz × 8

**Comment by tista500** [comment] 2017-02-04 03:41
@eypsum,

Let me know which apps were listed in that tray when crashing because you just did tracking down the issue.

**Comment by Aevyn** [comment] 2017-02-04 04:09
For me, **any** application that uses the Legacy Tray causes a gnome shell crash. 

I tested using Clementine, VLC (with tray enabled), VMware, and Spideroak. All caused a crash.

**Comment by Aevyn** [comment] 2017-02-04 04:20
I tracked down the issue by using the Hooli theme. Hooli uses modified adapta css files and is very similar in style to Adapta. Hooli does not cause crashes but adapta does. When I added legacy tray code to Hooli, gnome started to crash as well. It's not application specific. Whenever any program adds an icon to the legacy tray, there is an error.

**Comment by tista500** [comment] 2017-02-04 04:35
This happened gnome-shell 3.18.x only.
Committed: https://github.com/adapta-project/adapta-gtk-theme/commit/57b8419fcae727efd22e3c27a8409108026f8481

**Closed** 2017-02-04 04:36 UTC
Labels: bug

**Comment by esalgado** [comment] 2017-02-06 17:52
Hi! Seeing the answers to this thread, I downloaded Hooli myself to give it a try, and I can confirm that IT CRASHES ONCE at startup, just like Adapta does, in my computer.

Best regards,
