### ISSUE TITLE
Gnome Music title selection

### ISSUE THREAD

**Issue by Neristee** [adapta-project/adapta-gtk-theme#284] opened 2016-11-18 19:09 UTC
Hello, just reporting an issue on gnome music app.

**Distribution -** Fedora Rawhide
**Gtk+ 3.0 version** - 3.22.3-1
**Desktop environment -** Gnome

**Adapta version :**  Master 

**Related Application** : Gnome music

**Actual issue** : Whole songs become grey, as if they were all selected. 

**Steps to reproduce (if you knew)** : Cursor on an album's track in the gnome music app.

**Expected behaviour** : Songs greyed one by one, not as a whole when the mouse pointer is placed on them. 

**Other :** Thank you for your work.

**Issue : cursor on.**
 
![screenshot from 2016-11-18 20-05-58](https://cloud.githubusercontent.com/assets/15640409/20442804/7666fdec-adca-11e6-9300-346ca73263e3.png)

**No cursor :**
![screenshot from 2016-11-18 20-04-58](https://cloud.githubusercontent.com/assets/15640409/20442815/7dba2420-adca-11e6-8ddd-bd7b2b2b260a.png)

**Comment by tista500** [comment] 2016-11-19 08:12
o_O?
I could not reproduce with gnome-music 3.22.2:
![screenshot from 2016-11-19 16-26-51](https://cloud.githubusercontent.com/assets/6073622/20454152/e4a4c54a-ae7a-11e6-82b5-a45e1868bf2f.png)

**Comment by Neristee** [comment] 2016-11-19 08:32
Hello,

My version of gnome music is 3.23.1, and I installed the theme with the "enable-gtk-next" flag. I don't know if it's relevant.

**Comment by tista500** [comment] 2016-11-19 09:33
Omg, why don't you guys explain the current version of apps you used before asked... :/

Later I will see the git branch of gnome-music.

**Comment by Neristee** [comment] 2016-11-19 09:47
Sorry :/

I assumed you were on a so-called bleeding edge distro too, don't know why...

Hope you didn't waste too much time...

**Comment by tista500** [comment] 2016-11-19 10:32
See https://git.gnome.org/browse/gtk+/.
Officially Gtk+ devs did not release the tarball of Gtk+ 3.23.x yet. In this release cycle, Gnome application teams unveiled their 3.23.x series earlier than Gtk+ teams. In most cases, such release cylce may not be suitable for regular users who does neither debugging nor contributing...

If you were the debugger, you could bisect the differences between 3.22.x and 3.23.x before posting the issue, it also means you could mention me that "3.23.x seems to rewrite the AlbumWidget.ui or .py in 3.23.x cycle".

So I don't have any ideas why said like this:
> I assumed you were on a so-called bleeding edge distro too, don't know why...

Regards.

**Comment by Neristee** [comment] 2016-11-19 10:45
I just thought you were using a distro with gnome-music 3.23 provided by default. Nothing more... it wasn't an attack nor a way to show off...

I'm not a debugger, nor a contributor, just a fedora rawhide user (and user only) enjoying new things.

Anyway, just wanted to report this, you can close the issue or something. I'll not out-step any more.

Thank you for your time.
Cheers.

**Comment by tista500** [comment] 2016-11-19 12:52
Committed: https://github.com/adapta-project/adapta-gtk-theme/commit/b62e4f794a81978ec520e4999cab246427bdcae8

Closed.

**Closed by tista500** 2016-11-19 12:52 UTC
