### ISSUE TITLE
Some applications launch rather slowly when using Adapta

### ISSUE THREAD

**Issue by kpuljek** [adapta-project/adapta-gtk-theme#286] opened 2016-11-21 12:36 UTC
**Reporter info**

 ```
 * Distribution - Ubuntu 16.10
 * Gtk+ 3.0 version - 3.20
 * Desktop environment - Unity 7.5
 ```

**Adapta version (if you knew)**
3.89.1.5-0ubuntu1~yakkety1

**Related Application and/or Shell theming (or name of widget)**
Gnome-terminal, Nautilus

**Actual issue**
When I use Adapta terminal takes two or three seconds to launch. Nautilus (but only sometimes) as well. If I change to any other theme I've installed, it's almost instantaneous. I have noticed that it only happens if all terminals are closed, if I have one open the others pop up right away. The same goes for Nautilus. 

**Steps to reproduce (if you knew)**
Apply Adapta
Open terminal

**Expected behaviour**
Terminal should open instantly, but it takes a couple of seconds.

**Other Note (feature-request, question, etc...)**

**Comment by tista500** [comment] 2016-11-21 12:51
"Some" or "Gnome-Terminal and Nautilus", which?

**Comment by kpuljek** [comment] 2016-11-21 13:02
Fair question, sorry for being so vague, but to be honest Terminal and Nautilus are the ones I use the most.

I notice some delay when opening the image viewer (eye of gnome), but not nearly as much as with the terminal. So I didn't want to pinpoint the issue to just terminal and Nautilus (and it doesn't happen always with Nautilus) since I can't say that those are the only ones. Image viewer for sure, but not to the point of being unusable. 

But I can safely say that I've never had delays on Ambiance or Arc(-darker-darkest) with either of these, especially not the terminal.

If there is a method of measuring launch times for all applications I have installed with different themes, I'll gladly do so.

**Comment by tista500** [comment] 2016-11-21 13:13
> But I can safely say that I've never had delays on Ambiance or Arc(-darker-darkest) with either of these, especially not the terminal.

It's really unfair for me.
Because those themes do NOT have any Gtk+ 3.20/22 specific features, in other words, those themes are just forked styling from 3.18.x. But Adapta does NOT do such.

For example, Arc theme's `gtk.css` is just 190KB, but Adapta uses 1.84MB.
One of the mainly reason is they do not have to concern the geometry (aspect-ratios) precisely to render circular buttons, drop-shadows, animations, adaptive styling and much much more...

So please go back to other themes if you can't stand for the performance regressions what you said.

Regards.

**Comment by kpuljek** [comment] 2016-11-21 13:17
Okay, fair enough. I submitted this in case somebody else will perhaps add some additional information. More than once I've witnessed bugs being reported and then a sudden influx of "me too's" ends up in a solution within a day or so.  Maybe this isn't even a widespread thing, Unity is a mess anyway. I'll keep playing with it and if I get any concrete information, I'll let you know. Otherwise, great job with the theme, it's really beautiful.

**Comment by tista500** [comment] 2016-11-21 14:07
If we could implement gresource compilation for Gtk+ theming, it may improves rendering performance a bit better, I think...

Regards.

**Comment by bil-elmoussaoui** [comment] 2016-11-21 17:04
@tista500 This might help https://github.com/horst3180/arc-theme/pull/656

**Comment by tista500** [comment] 2016-11-21 17:13
Adapta is under GPLv2.0 but Arc is under v3. So we can't steal their codes.

Already Satya explained the how-to: http://wibblystuff.blogspot.jp/2012/06/building-binary-for-gtk3-theme.html

Regards.

**Comment by bil-elmoussaoui** [comment] 2016-11-21 17:17
It wasn't about stealing codes, it's just to get an idea how things works :+1:

**Comment by tista500** [comment] 2016-11-21 22:14
Committed 1st trial: https://github.com/adapta-project/adapta-gtk-theme/commit/9af76f213a1041b3509aedcdec5e534626f98db2

**Comment by tista500** [comment] 2016-11-24 08:19
Committed: 2nd trial: https://github.com/adapta-project/adapta-gtk-theme/commit/19970a1f377b6c90d151b5876bf717826b99cd0c

**Comment by ronisbr** [comment] 2016-11-25 01:47
To build Adapta, I needed to add this package:

* gdk-pixbuf-loader-rsvg

Otherwise it fails because it was not finding `gtk.gresource`. Do you think it is good to add this information to README?

**Comment by tista500** [comment] 2016-11-25 06:39
@ronisbr,

Stop posting off-topic.

**Comment by ronisbr** [comment] 2016-11-25 10:29
@tista500,

HI, I don't think it is off-topic, the problem I described started with your 1st trial to introduce gresource compilation.

**Comment by tista500** [comment] 2016-11-25 10:46
Hey hey, please read the title... :(

And your post seems to be related to openSUSE packaging specific, please...

**Comment by tista500** [comment] 2016-11-25 11:46
Committed: 3rd trial:https://github.com/adapta-project/adapta-gtk-theme/commit/5308aa8b1eb43df6fa17355e22b7b94da3bb0d3c

Closed

**Closed by tista500** 2016-11-25 11:46 UTC
Labels: enhancement
