### ISSUE TITLE
Feature request: light variant

### ISSUE THREAD

**Issue by Hombremaledicto** [adapta-project/adapta-gtk-theme#568] opened 2017-11-25 17:11 UTC
Is there any chance for a light (specifically headerbar & titlebar colors) variant in the future?

**Comment by tista500** [comment] 2017-11-25 18:26
The duplicate of #494.

**Closed** 2017-11-25 18:41 UTC
Labels: duplicate

**Comment by tista500** [comment] 2017-11-25 18:46
At least I don't have much time in 2017, so the next year I may or may not re-track #494, I can't promise though.

**Comment by Hombremaledicto** [comment] 2017-11-25 18:49
No problem, i might look to work on it myself, in case you can at least review and accept the code
