### ISSUE TITLE
Jet Brains applications

### ISSUE THREAD

**Issue by pzientar** [adapta-project/adapta-gtk-theme#283] opened 2016-11-18 09:00 UTC
Hi there,
awsome theme, great work.

Could you take a look at Jet Brains apps (like Android Studio, Pycharm, Webstorm, PHP Storm, IntelliJ)?

Is there any possibility to make them looks better with Adapta?

**Comment by tista500** [comment] 2016-11-18 09:59
This is the duplicate of this issue: #247.

Unfortunately there's few things to do for their apps.
Those Java Gtk+ backends are too poor to implement Adapta theming now.

Regards.

**Closed** 2016-11-20 15:48 UTC
Labels: duplicate, wontfix
