### ISSUE TITLE
Taskbar and volume value are missing on Mate

### ISSUE THREAD

**Issue by Zulgrib** [adapta-project/adapta-gtk-theme#492] opened 2017-08-26 09:38 UTC
**Reporter info**

 ```
 * Distribution - Mint 18.2
 * Gtk+ 3.0 version - 3.20.8
 * Gtk+ 2.0 version - 2.24.30
 * Desktop environment - Mate 1.18
 * Display server protocol - X11
 * gtk2-engines-murrine - 0.98.2
 * gtk2-engines-pixbuf - 2.24.30
 ```

**Adapta version (if you knew)**
3.91.2.93

**Related Application and/or Shell theming (or name of widget)**

**Actual issue**
Task bar is transparent
Audio/Brightness has no bar

**Steps to reproduce (if you knew)**
Apply theme
Increase/decrease volume or brightness using hotkeys

**Expected behaviour**
Not having an invisible taskbar
Seeing a bar indicating resulting volume or brightness level

**Other Note (feature-request, question, etc...)**
It worked some version before, it didn't break with this specific version but did not have time to report before.

https://lut.im/CVjECGxvJl/HTPKQKpiLy1ePhGF.png

**Comment by tista500** [comment] 2017-08-26 12:44
What is the *taskbar*? ProgressBar? o_O?

Anyway I could not reproduce with Mate-settings-daemon 1.18.1 & Gtk+ 3.22.19 on my Artful:
![screenshot from 2017-08-26 20-12-10](https://user-images.githubusercontent.com/6073622/29741421-ac30fe36-8aa7-11e7-85c0-b3c6b43678c3.png)

**Comment by Zulgrib** [comment] 2017-08-26 23:29
The taskbar is the bar at the very bottom of my screenshot where menu, three shortcuts, currently running GUI software are listed and notification area.
You can see a part of it is literally missing and we see chrome's white background instead.

**Comment by tista500** [comment] 2017-08-28 15:09
> The taskbar is the bar at the very bottom of my screenshot where menu, three shortcuts, currently running GUI software are listed and notification area.

Mate-panel: https://github.com/mate-desktop/mate-panel

**Comment by tista500** [comment] 2017-08-29 08:11
I could not reproduce with M-S-D 1.16.0-1 & Gtk+ 3.20.9-1ubuntu2.1 either.

**Comment by tista500** [comment] 2017-09-08 07:23
I close this because I could nor reproduce anyhow.

**Closed by tista500** 2017-09-08 07:23 UTC
Labels: unable to reproduce
